index:
    path:         /
    controller:   App\Controller\FrontController::index

ajax_tricks:
    path:         /{page}
    controller:   App\Controller\FrontController::ajaxTricks
    condition:    "request.isXmlHttpRequest()"
    requirements:
        page:     '\d+'

trick:
    path:         /trick-{id}
    controller:   App\Controller\FrontController:trick
    requirements:
        page:     '\d+'
